import assert from 'node:assert/strict';
import test from 'node:test';
import { performance } from 'node:perf_hooks';
import { TranspileError, transpile } from '../src/index.js';

function expectTranspileError(source, pattern = /unsupported|not supported|supported|must/i) {
  assert.throws(
    () => transpile(source, { filename: 'hardening.js' }),
    (error) => {
      assert.ok(error instanceof TranspileError);
      assert.ok(error.diagnostics.length > 0);
      assert.match(error.diagnostics[0].message, pattern);
      return true;
    },
  );
}

test('golden output for a minimal boot script stays stable', () => {
  const source = `import { task, telemetry } from 'satellite-os'
function boot() {
  telemetry.emit('boot.ok', true)
}
task.once('boot', boot)
task.start()
`;

  const { code } = transpile(source, { filename: 'golden.js' });

  assert.equal(code, `// Generated by satjs-cpp. Do not edit by hand.
// Source: golden.js

#include <cstdint>
#include <string>
#include <vector>
#include "satellite_os.hpp"

auto boot() {
  satellite::telemetry::emit("boot.ok", true);
}

void satellite_main() {
  satellite::task::once("boot", [&](auto&&... args) { return boot(args...); });
  satellite::task::start();
}
`);
});

test('unsupported AST categories fail with diagnostics instead of crashing', () => {
  const snippets = [
    `import { task } from 'satellite-os'; task.once('boot', () => { const { x } = payload })`,
    `import { task } from 'satellite-os'; task.once('boot', () => { const xs = [1, ...ys] })`,
    `import { task } from 'satellite-os'; task.once('boot', () => { const o = { [name]: 1 } })`,
    `import { task } from 'satellite-os'; task.once('boot', () => { const xs = [1,,2] })`,
    `import { task } from 'satellite-os'; task.once('boot', () => { const x = obj?.value })`,
    `import { task } from 'satellite-os'; task.once('boot', () => { switch (mode) { case 1: break } })`,
  ];

  for (const snippet of snippets) {
    expectTranspileError(snippet);
  }
});

test('performance smoke for a larger boot manifest', () => {
  const registrations = Array.from({ length: 250 }, (_, index) => `task.once('boot-${index}', boot)`).join('\n');
  const source = `import { task, telemetry } from 'satellite-os'
function boot() { telemetry.emit('boot.ok', true) }
${registrations}
task.start()
`;

  const started = performance.now();
  const { code, ir } = transpile(source, { filename: 'large.js' });
  const elapsedMs = performance.now() - started;

  assert.equal(ir.boot.length, 251);
  assert.match(code, /boot-249/);
  assert.ok(elapsedMs < 2000, `expected transpilation under 2s, got ${elapsedMs}ms`);
});
