import { CppWriter } from './cpp-writer.js';
import { TranspileError, diagnostic } from './diagnostics.js';
import {
  SATELLITE_MODULE,
  cppString,
  isSatelliteNamespace,
  modulePathToHeader,
} from './satellite-api.js';

const CPP_RESERVED = new Set([
  'alignas', 'alignof', 'and', 'and_eq', 'asm', 'atomic_cancel', 'atomic_commit',
  'atomic_noexcept', 'auto', 'bitand', 'bitor', 'bool', 'break', 'case', 'catch',
  'char', 'char8_t', 'char16_t', 'char32_t', 'class', 'compl', 'concept', 'const',
  'consteval', 'constexpr', 'constinit', 'const_cast', 'continue', 'co_await',
  'co_return', 'co_yield', 'decltype', 'default', 'delete', 'do', 'double',
  'dynamic_cast', 'else', 'enum', 'explicit', 'export', 'extern', 'false', 'float',
  'for', 'friend', 'goto', 'if', 'inline', 'int', 'long', 'mutable', 'namespace',
  'new', 'noexcept', 'not', 'not_eq', 'nullptr', 'operator', 'or', 'or_eq',
  'private', 'protected', 'public', 'reflexpr', 'register', 'reinterpret_cast',
  'requires', 'return', 'short', 'signed', 'sizeof', 'static', 'static_assert',
  'static_cast', 'struct', 'switch', 'synchronized', 'template', 'this',
  'thread_local', 'throw', 'true', 'try', 'typedef', 'typeid', 'typename', 'union',
  'unsigned', 'using', 'virtual', 'void', 'volatile', 'wchar_t', 'while', 'xor',
  'xor_eq',
]);

export class SatelliteCppEmitter {
  constructor({ filename = '<input>', runtimeHeader = 'satellite_os.hpp' } = {}) {
    this.filename = filename;
    this.runtimeHeader = runtimeHeader;
    this.systemIncludes = new Set(['<cstdint>', '<string>', '<vector>']);
    this.localIncludes = new Set([runtimeHeader]);
    this.satelliteImports = new Map();
    this.localImports = new Map();
  }

  emitMissionProgram(mission) {
    this.satelliteImports = new Map(mission.satelliteImports.map(({ local, imported }) => [local, imported]));
    for (const include of mission.localIncludes) {
      this.localIncludes.add(include);
    }

    const writer = new CppWriter();
    writer.line('// Generated by satjs-cpp. Do not edit by hand.');
    writer.line(`// Source: ${this.filename}`);
    writer.line();

    for (const include of [...this.systemIncludes].sort()) {
      writer.line(`#include ${include}`);
    }
    for (const include of [...this.localIncludes].sort()) {
      writer.line(`#include ${cppString(include)}`);
    }
    writer.line();

    for (const fn of mission.functions) {
      this.emitFunctionDeclaration(fn.node, writer);
      writer.line();
    }

    writer.block('void satellite_main()', () => {
      if (mission.constants.length === 0 && mission.boot.length === 0) {
        writer.line('// No top-level scheduler or hardware registration statements were found.');
      }
      for (const declaration of mission.constants) {
        this.emitVariableDeclaration(declaration.node, writer);
      }
      for (const operation of mission.boot) {
        this.emitBootOperation(operation, writer);
      }
    });

    return writer.toString();
  }

  emit(ast) {
    this.collectImports(ast.program.body);
    const mission = {
      satelliteImports: [...this.satelliteImports.entries()].map(([local, imported]) => ({ local, imported })),
      localIncludes: [...this.localIncludes].filter((include) => include !== this.runtimeHeader),
      functions: ast.program.body
        .filter((statement) => statement.type === 'FunctionDeclaration')
        .map((node) => ({ kind: 'MissionFunction', name: node.id.name, node })),
      constants: [],
      boot: ast.program.body
        .filter((statement) => statement.type !== 'ImportDeclaration' && statement.type !== 'FunctionDeclaration')
        .map((statement) => ({ kind: 'RawStatement', statement, node: statement })),
    };
    return this.emitMissionProgram(mission);
  }

  collectImports(statements) {
    for (const statement of statements) {
      if (statement.type !== 'ImportDeclaration') {
        continue;
      }
      const source = statement.source.value;
      if (source === SATELLITE_MODULE) {
        for (const specifier of statement.specifiers) {
          if (specifier.type !== 'ImportSpecifier') {
            this.unsupported(specifier, 'Only named imports from satellite-os are supported.');
          }
          this.satelliteImports.set(specifier.local.name, specifier.imported.name);
        }
        continue;
      }
      if (source.startsWith('.')) {
        const header = modulePathToHeader(source);
        this.localIncludes.add(header);
        for (const specifier of statement.specifiers) {
          if (specifier.local?.name) {
            this.localImports.set(specifier.local.name, header);
          }
        }
        continue;
      }
      this.unsupported(
        statement,
        `Unsupported import source ${source}. Only satellite-os and relative driver/helper imports are supported.`,
        'Move platform-specific libraries behind satellite-os drivers, or add an explicit lowering rule.',
      );
    }
  }

  emitBootOperation(operation, writer) {
    switch (operation.kind) {
      case 'RegisterDevice':
        return writer.line(`satellite::device::register_driver<${operation.driverType}>(${this.emitExpression(operation.name)}, ${this.emitExpression(operation.options)});`);
      case 'RegisterFaultHandler':
        return writer.line(`satellite::fault::handle(${this.emitExpression(operation.faultName)}, ${this.emitCallbackRef(operation.callback)});`);
      case 'RegisterTask': {
        const args = [this.emitExpression(operation.name)];
        if (operation.mode === 'every') {
          args.push(this.emitExpression(operation.period));
        }
        args.push(this.emitCallbackRef(operation.callback));
        return writer.line(`satellite::task::${operation.mode}(${args.join(', ')});`);
      }
      case 'StartScheduler':
        return writer.line('satellite::task::start();');
      case 'RawStatement':
        return this.emitStatement(operation.statement, writer);
      default:
        return this.unsupported(operation.node, `Unsupported boot operation ${operation.kind}.`);
    }
  }

  emitCallbackRef(callback) {
    if (callback.kind === 'CallbackRef') {
      return this.emitCallbackArgument(callback.node);
    }
    if (callback.kind === 'InlineCallback') {
      return this.emitExpression(callback.node);
    }
    return this.unsupported(callback.node, `Unsupported callback ${callback.kind}.`);
  }

  emitFunctionDeclaration(node, writer) {
    if (!node.id?.name) {
      this.unsupported(node, 'Function declarations must be named so tasks and faults are traceable.');
    }
    const params = node.params.map((param) => this.emitParameter(param)).join(', ');
    writer.block(`auto ${this.emitIdentifier(node.id)}(${params})`, () => {
      this.emitBlockBody(node.body, writer);
    });
  }

  emitStatement(node, writer) {
    switch (node.type) {
      case 'VariableDeclaration':
        return this.emitVariableDeclaration(node, writer);
      case 'ExpressionStatement':
        return writer.line(`${this.emitExpression(node.expression)};`);
      case 'BlockStatement':
        return writer.block('', () => this.emitBlockBody(node, writer));
      case 'IfStatement':
        return this.emitIfStatement(node, writer);
      case 'ReturnStatement':
        return writer.line(node.argument ? `return ${this.emitExpression(node.argument)};` : 'return;');
      case 'TryStatement':
        return this.emitTryStatement(node, writer);
      case 'ThrowStatement':
        return writer.line(`throw ${this.emitExpression(node.argument)};`);
      case 'EmptyStatement':
        return writer.line();
      case 'FunctionDeclaration':
        return this.emitFunctionDeclaration(node, writer);
      case 'ForStatement':
        return this.emitForStatement(node, writer);
      case 'WhileStatement':
        return this.emitWhileStatement(node, writer);
      case 'BreakStatement':
        return writer.line('break;');
      case 'ContinueStatement':
        return writer.line('continue;');
      default:
        return this.unsupported(node, `Unsupported statement node ${node.type}.`);
    }
  }

  emitBlockBody(block, writer) {
    for (const statement of block.body) {
      this.emitStatement(statement, writer);
    }
  }

  emitVariableDeclaration(node, writer) {
    // JavaScript const freezes the binding, not the object. Emit mutable C++ locals
    // so resource handles can still call lifecycle methods such as close().
    const qualifier = 'auto';
    for (const declarator of node.declarations) {
      if (declarator.id.type !== 'Identifier') {
        this.unsupported(declarator.id, 'Only simple identifier variable declarations are supported in the first implementation.');
      }
      const name = this.emitIdentifier(declarator.id);
      const init = declarator.init ? ` = ${this.emitExpression(declarator.init)}` : '';
      writer.line(`${qualifier} ${name}${init};`);
    }
  }

  emitIfStatement(node, writer) {
    writer.line(`if (${this.emitExpression(node.test)}) {`);
    writer.indent();
    this.emitStatementAsBody(node.consequent, writer);
    writer.dedent();
    if (!node.alternate) {
      writer.line('}');
      return;
    }
    writer.line('} else {');
    writer.indent();
    this.emitStatementAsBody(node.alternate, writer);
    writer.dedent();
    writer.line('}');
  }

  emitStatementAsBody(node, writer) {
    if (node.type === 'BlockStatement') {
      this.emitBlockBody(node, writer);
      return;
    }
    this.emitStatement(node, writer);
  }

  emitTryStatement(node, writer) {
    writer.line('try {');
    writer.indent();
    this.emitBlockBody(node.block, writer);
    writer.dedent();
    if (node.handler) {
      const param = node.handler.param ? this.emitPatternName(node.handler.param) : 'e';
      writer.line(`} catch (const satellite::Error& ${param}) {`);
      writer.indent();
      this.emitBlockBody(node.handler.body, writer);
      writer.dedent();
      writer.line('}');
      return;
    }
    writer.line('}');
    if (node.finalizer) {
      this.unsupported(node.finalizer, 'try/finally is not supported because deterministic cleanup should use explicit close/release calls.');
    }
  }

  emitForStatement(node, writer) {
    const init = node.init ? this.emitForInit(node.init) : '';
    const test = node.test ? this.emitExpression(node.test) : '';
    const update = node.update ? this.emitExpression(node.update) : '';
    writer.line(`for (${init}; ${test}; ${update}) {`);
    writer.indent();
    this.emitStatementAsBody(node.body, writer);
    writer.dedent();
    writer.line('}');
  }

  emitForInit(node) {
    if (node.type === 'VariableDeclaration') {
      if (node.declarations.length !== 1) {
        this.unsupported(node, 'for-loop initializers support exactly one declaration.');
      }
      const declarator = node.declarations[0];
      if (declarator.id.type !== 'Identifier') {
        this.unsupported(declarator.id, 'for-loop declarations require an identifier.');
      }
      const qualifier = 'auto';
      const init = declarator.init ? ` = ${this.emitExpression(declarator.init)}` : '';
      return `${qualifier} ${this.emitIdentifier(declarator.id)}${init}`;
    }
    return this.emitExpression(node);
  }

  emitWhileStatement(node, writer) {
    writer.line(`while (${this.emitExpression(node.test)}) {`);
    writer.indent();
    this.emitStatementAsBody(node.body, writer);
    writer.dedent();
    writer.line('}');
  }

  emitExpression(node) {
    switch (node.type) {
      case 'Identifier':
        return this.emitIdentifier(node);
      case 'NumericLiteral':
      case 'StringLiteral':
      case 'BooleanLiteral':
      case 'NullLiteral':
        return this.emitLiteral(node);
      case 'ArrayExpression':
        return this.emitArrayExpression(node);
      case 'ObjectExpression':
        return this.emitObjectExpression(node);
      case 'CallExpression':
        return this.emitCallExpression(node);
      case 'AwaitExpression':
        return this.emitExpression(node.argument);
      case 'MemberExpression':
        return this.emitMemberExpression(node);
      case 'BinaryExpression':
      case 'LogicalExpression':
        return `(${this.emitExpression(node.left)} ${this.emitOperator(node.operator)} ${this.emitExpression(node.right)})`;
      case 'UnaryExpression':
        return `(${node.operator}${node.operator.length > 2 ? ' ' : ''}${this.emitExpression(node.argument)})`;
      case 'UpdateExpression':
        return node.prefix
          ? `${node.operator}${this.emitExpression(node.argument)}`
          : `${this.emitExpression(node.argument)}${node.operator}`;
      case 'AssignmentExpression':
        return `(${this.emitExpression(node.left)} ${this.emitOperator(node.operator)} ${this.emitExpression(node.right)})`;
      case 'ConditionalExpression':
        return `(${this.emitExpression(node.test)} ? ${this.emitExpression(node.consequent)} : ${this.emitExpression(node.alternate)})`;
      case 'ArrowFunctionExpression':
      case 'FunctionExpression':
        return this.emitFunctionExpression(node);
      case 'TemplateLiteral':
        return this.emitTemplateLiteral(node);
      case 'NewExpression':
        return `${this.emitExpression(node.callee)}(${node.arguments.map((arg) => this.emitExpression(arg)).join(', ')})`;
      default:
        return this.unsupported(node, `Unsupported expression node ${node.type}.`);
    }
  }

  emitIdentifier(node) {
    if (node.name === 'undefined') {
      return 'nullptr';
    }
    if (CPP_RESERVED.has(node.name)) {
      return `${node.name}_`;
    }
    return node.name;
  }

  emitPatternName(node) {
    if (node.type !== 'Identifier') {
      this.unsupported(node, 'Only identifier parameters and catch bindings are supported.');
    }
    return this.emitIdentifier(node);
  }

  emitParameter(node) {
    return `auto&& ${this.emitPatternName(node)}`;
  }

  emitLiteral(node) {
    switch (node.type) {
      case 'NumericLiteral':
        return (node.extra?.raw ?? String(node.value)).replaceAll('_', '');
      case 'StringLiteral':
        return cppString(node.value);
      case 'BooleanLiteral':
        return node.value ? 'true' : 'false';
      case 'NullLiteral':
        return 'nullptr';
      default:
        return this.unsupported(node, `Unsupported literal ${node.type}.`);
    }
  }

  emitArrayExpression(node) {
    const elements = node.elements.map((element) => {
      if (!element) {
        this.unsupported(node, 'Sparse arrays are not supported.');
      }
      return this.emitExpression(element);
    });
    return `satellite::Array{${elements.join(', ')}}`;
  }

  emitObjectExpression(node) {
    const pairs = node.properties.map((property) => {
      if (property.type !== 'ObjectProperty') {
        this.unsupported(property, 'Object spread and methods are not supported in mission configuration objects.');
      }
      if (property.computed) {
        this.unsupported(property, 'Computed object keys are not supported in mission configuration objects.');
      }
      return `{${this.emitObjectKey(property.key)}, ${this.emitExpression(property.value)}}`;
    });
    return `satellite::Object{${pairs.join(', ')}}`;
  }

  emitObjectKey(node) {
    switch (node.type) {
      case 'Identifier':
        return cppString(node.name);
      case 'StringLiteral':
        return cppString(node.value);
      case 'NumericLiteral':
        return cppString(node.extra?.raw ?? String(node.value));
      default:
        return this.unsupported(node, `Unsupported object key ${node.type}.`);
    }
  }

  emitCallExpression(node) {
    const parts = this.getStaticMemberParts(node.callee);

    if (parts?.length === 2 && parts[0] === 'Date' && parts[1] === 'now') {
      return 'satellite::clock::now_ms()';
    }

    if (parts?.length === 2 && parts[0] === 'Uint8Array' && parts[1] === 'of') {
      return `satellite::Bytes{${node.arguments.map((arg) => this.emitExpression(arg)).join(', ')}}`;
    }

    if (parts?.length >= 2) {
      const namespaceName = this.resolveSatelliteImport(parts[0]);
      if (isSatelliteNamespace(namespaceName)) {
        return this.emitSatelliteCall(namespaceName, parts.slice(1), node.arguments, node);
      }
    }

    const args = node.arguments.map((arg) => this.emitExpression(arg)).join(', ');
    if (node.callee.type === 'MemberExpression') {
      const object = this.emitExpression(node.callee.object);
      const property = node.callee.computed
        ? `[${this.emitExpression(node.callee.property)}]`
        : `.${this.emitPropertyName(node.callee.property)}`;
      return `${object}${property}(${args})`;
    }
    return `${this.emitExpression(node.callee)}(${args})`;
  }

  emitSatelliteCall(namespaceName, memberParts, args, node) {
    const method = memberParts.join('::');
    if (namespaceName === 'device' && method === 'register') {
      if (args.length !== 3) {
        this.unsupported(node, 'device.register expects exactly (name, DriverType, options).');
      }
      const [nameArg, driverArg, optionsArg] = args;
      if (driverArg.type !== 'Identifier') {
        this.unsupported(driverArg, 'device.register currently expects the driver type argument to be an identifier.');
      }
      return `satellite::device::register_driver<${this.emitIdentifier(driverArg)}>(${this.emitExpression(nameArg)}, ${this.emitExpression(optionsArg)})`;
    }

    if (namespaceName === 'fault' && method === 'handle') {
      if (args.length !== 2) {
        this.unsupported(node, 'fault.handle expects exactly (name, handler).');
      }
      return `satellite::fault::handle(${this.emitExpression(args[0])}, ${this.emitCallbackArgument(args[1])})`;
    }

    if (namespaceName === 'task' && ['once', 'every', 'on'].includes(method)) {
      return this.emitTaskRegistration(method, args, node);
    }

    const loweredName = `satellite::${namespaceName}::${method}`;
    return `${loweredName}(${args.map((arg) => this.emitExpression(arg)).join(', ')})`;
  }

  emitTaskRegistration(method, args, node) {
    const expected = method === 'every' ? 3 : 2;
    if (args.length !== expected) {
      this.unsupported(node, `task.${method} expects ${expected} arguments in the satellite-os contract.`);
    }
    const loweredArgs = args.map((arg, index) => {
      const isCallback = index === args.length - 1;
      return isCallback ? this.emitCallbackArgument(arg) : this.emitExpression(arg);
    });
    return `satellite::task::${method}(${loweredArgs.join(', ')})`;
  }

  emitCallbackArgument(node) {
    if (node.type === 'Identifier') {
      const name = this.emitIdentifier(node);
      return `[&](auto&&... args) { return ${name}(args...); }`;
    }
    return this.emitExpression(node);
  }

  emitMemberExpression(node) {
    const object = this.emitExpression(node.object);
    if (node.computed) {
      return `${object}[${this.emitExpression(node.property)}]`;
    }
    return `${object}.${this.emitPropertyName(node.property)}`;
  }

  emitPropertyName(node) {
    if (node.type === 'Identifier') {
      return this.emitIdentifier(node);
    }
    if (node.type === 'PrivateName') {
      this.unsupported(node, 'Private fields are not part of the supported mission script subset.');
    }
    return this.emitExpression(node);
  }

  emitFunctionExpression(node) {
    const params = node.params.map((param) => this.emitParameter(param)).join(', ');
    const writer = new CppWriter();
    writer.line(`[&](${params}) {`);
    writer.indent();
    if (node.body.type === 'BlockStatement') {
      this.emitBlockBody(node.body, writer);
    } else {
      writer.line(`return ${this.emitExpression(node.body)};`);
    }
    writer.dedent();
    writer.line('}');
    return writer.toString().trimEnd();
  }

  emitTemplateLiteral(node) {
    if (node.expressions.length > 0) {
      this.unsupported(node, 'Template literals with interpolation are not supported yet; use explicit string constants.');
    }
    return cppString(node.quasis.map((quasi) => quasi.value.cooked).join(''));
  }

  emitOperator(operator) {
    switch (operator) {
      case '===':
        return '==';
      case '!==':
        return '!=';
      case '**':
        this.unsupported({ type: 'BinaryExpression' }, 'Exponentiation is not supported; call a mission math helper explicitly.');
        break;
      default:
        return operator;
    }
  }

  getStaticMemberParts(node) {
    if (node.type === 'Identifier') {
      return [node.name];
    }
    if (node.type !== 'MemberExpression' || node.computed) {
      return undefined;
    }
    const objectParts = this.getStaticMemberParts(node.object);
    if (!objectParts || node.property.type !== 'Identifier') {
      return undefined;
    }
    return [...objectParts, node.property.name];
  }

  resolveSatelliteImport(localName) {
    return this.satelliteImports.get(localName) ?? localName;
  }

  unsupported(node, message, hint) {
    const diagnostics = [diagnostic({ code: 'SATJS_UNSUPPORTED_SYNTAX', message, node, hint })];
    throw new TranspileError(message, diagnostics);
  }
}
